icons_format = "<span font_family='FiraCode Nerd Font'>{icon}</span>"

[theme]
theme = "nord-dark"
[icons]
icons = "awesome6"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
short = " $icon %R "

[[block]]
block = "memory"
format = " $icon $mem_used.eng(w:3,u:B,p:M) $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_used.eng(w:3,u:B,p:M) $swap_used_percents.eng(w:1) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
format = " $icon $1m.eng(w:3) "
interval = 1

[[block]]
block = "net"
format_alt = " $icon  {$signal_strength $frequency|Wired connection} "
interval = 1

#[[block]]
#block = "custom"
# ⌨ == '\xE2\x8C\xA8'
#cycle = ["xinput enable 'AT Translated Set 2 keyboard'; echo '⌨ ON'", "xinput disable 'AT Translated Set 2 keyboard'; echo '⌨ OFF'"]

[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "

